class Library {
  static List<String> letters = [
    '→',
    'A',
    'Ä',
    'B',
    'C',
    'D',
    'E',
    'F',
    'G',
    'H',
    'I',
    'J',
    'K',
    'L',
    'M',
    'N',
    'O',
    'Ö',
    'P',
    'Q',
    'R',
    'S',
    'T',
    'U',
    'Ü',
    'V',
    'W',
    'X',
    'Y',
    'Z',
  ];

  static List<String> digits = [
    '→',
    '0',
    '1',
    '2',
    '3',
    '4',
    '5',
    '6',
    '7',
    '8',
    '9',
    ',',
  ];

  static List<String> words = [
    'MAMA',
    'PAPA',
    'HUND',
    'KATZE',
    'MAUS',
    'HASE',
    'AFFE',
    'BÄR',
    'FISCH',
    'HAUS',
    'BAUM',
    'BLUME',
    'BALL',
    'PUPPE',
    'STIFT',
    'OHR',
    'NASE',
    'MUND',
    'BEIN',
    'BANANE',
    'APFEL',
    'BIRNE',
    'GURKE',
    'TOMATE',
    'SEIL',
    'AUGE',
    'FREUND',
    'HOSE',
    'SCHUH',
    'SCHLÜSSEL',
    'KLO',
    'LOCH',
    'EI',
    'EIS',
    'EINS',
    'ZIEL',
    'KLASSE',
    'TASSE',
    'TELLER',
    'LÖFFEL',
    'GABEL',
    'MESSER',
    'FLUSS',
    'JAHR',
    'HUNGER',
    'SPANISCHE INQUISITION',
    'ÜBUNG',
    'PFERD',
    'ÜBUNG',
    'ZAHL',
    'SCHNEE',
    'SCHULE',
    'ZAHN',
    'BAHN',
    'ZEH',
    'FINGER',
    'BLOCK',
    'ZEIT',
    'ZUCKER',
    'QUATSCH',
    'GLÜCK',
    'KÜCHE',
    'BLÜTE',
    'MANN',
    'FRAU',
    'KIND',
    'KÄFER',
    'BABY',
    'LÖWE',
    'STÜCK',
    'POLIZEI',
    'FEHLER',
    'KÄFER',
    'WURST',
    'MÜTZE',
    'JACKE',
    'SCHATZ',
    'SCHRANK',
    'TISCH',
    'MASCHINE',
    'OMA',
    'OPA',
    'HAMMER',
    'ECKE',
    'SCHERE',
    'BOOT',
    'ZOO',
    'BUS',
    'SCHRECK',
    'EULE',
    'FEUER',
    'KREUZ',
    'PO',
  ];

  static List<String> numbers = [
    '1',
    '10',
    '100',
    '1000',
    '1000000',
    '83,5',
    '77',
    '42',
    '7',
    '0,5',
    '11',
    '30',
    '16',
    '50',
    '95',
    '68',
    '0',
    '13',
    '34',
    '15',
    '1,2',
    '10',
    '46',
    '9',
    '49',
    '21',
    '13',
    '36',
    '28',
    '49',
    '99,99',
    '18',
    '8',
    '13',
    '33',
    '67',
    '22',
    '48',
    '4',
    '21',
    '78',
    '10',
    '85',
    '80',
    '75',
    '0',
    '49',
    '63',
    '53',
    '67',
    '70',
    '89',
    '72',
    '38',
    '53',
    '45',
    '30',
    '95',
    '54',
    '66',
    '38',
    '601',
    '870',
    '815',
    '724',
    '151',
    '108',
    '128',
    '425',
    '16',
    '548',
    '709',
    '155',
    '982',
    '386',
    '683',
    '173',
    '301',
    '714',
    '58',
    '345',
    '7818291',
    '663265',
    '8197347',
    '3438812',
    '3028078',
    '4243830',
    '6368547',
    '1462124',
    '3076702',
    '6673424',
  ];

  static Map<String, String> languageNames = {
    'ab': 'Abchasisch',
    'aa': 'Afar',
    'af': 'Afrikaans',
    'ak': 'Akan',
    'sq': 'Albanisch',
    'am': 'Amharisch',
    'ar': 'Arabisch',
    'an': 'Aragonesisch',
    'hy': 'Armenisch',
    'as': 'Assamesisch',
    'av': 'Avarisch',
    'ae': 'Avestisch',
    'ay': 'Aymara',
    'az': 'Aserbaidschanisch',
    'bm': 'Bambara',
    'ba': 'Baschkirisch',
    'eu': 'Baskisch',
    'be': 'Weißrussisch',
    'bn': 'Bengalisch',
    'bh': 'Bihari',
    'bi': 'Bislama',
    'bs': 'Bosnisch',
    'br': 'Bretonisch',
    'bg': 'Bulgarisch',
    'my': 'Birmanisch',
    'ca': 'Katalanisch, Valencianisch',
    'ch': 'Chamorro',
    'ce': 'Tschetschenisch',
    'ny': 'Chichewa',
    'zh': 'Chinesisch',
    'cv': 'Tschuwaschisch',
    'kw': 'Kornisch',
    'co': 'Korsisch',
    'cr': 'Cree',
    'hr': 'Kroatisch',
    'cs': 'Tschechisch',
    'da': 'Dänisch',
    'dv': 'Dhivehi',
    'nl': 'Niederländisch, Belgisches Niederländisch',
    'dz': 'Dzongkha',
    'en': 'Englisch',
    'eo': 'Esperanto',
    'et': 'Estnisch',
    'ee': 'Ewe',
    'fo': 'Färöisch',
    'fj': 'Fidschi',
    'fi': 'Finnisch',
    'fr': 'Französisch',
    'ff': 'Fulfulde',
    'gl': 'Galicisch, Galegisch',
    'ka': 'Georgisch',
    'de': 'Deutsch',
    'el': 'Griechisch',
    'gn': 'Guaraní',
    'gu': 'Gujarati',
    'ht': 'Haitianisch',
    'ha': 'Hausa',
    'he': 'Hebräisch',
    'hz': 'Otjiherero',
    'hi': 'Hindi',
    'ho': 'Hiri Motu',
    'hu': 'Ungarisch',
    'ia': 'Interlingua',
    'id': 'Indonesisch',
    'ie': 'Interlingue',
    'ga': 'Irisch',
    'ig': 'Igbo',
    'ik': 'Inupiaq',
    'io': 'Ido',
    'is': 'Isländisch',
    'it': 'Italienisch',
    'iu': 'Inuktitut',
    'ja': 'Japanisch',
    'jv': 'Javanisch',
    'kl': 'Grönländisch, Kalaallisut',
    'kn': 'Kannada',
    'kr': 'Kanuri',
    'ks': 'Kashmiri',
    'kk': 'Kasachisch',
    'km': 'Khmer',
    'ki': 'Kikuyu',
    'rw': 'Kinyarwanda, Ruandisch',
    'ky': 'Kirgisisch',
    'kv': 'Komi',
    'kg': 'Kikongo',
    'ko': 'Koreanisch',
    'ku': 'Kurdisch',
    'kj': 'oshiKwanyama',
    'la': 'Latein',
    'lb': 'Luxemburgisch',
    'lg': 'Luganda',
    'li': 'Limburgisch, Südniederfränkisch',
    'ln': 'Lingála',
    'lo': 'Laotisch',
    'lt': 'Litauisch',
    'lu': 'Kiluba',
    'lv': 'Lettisch',
    'gv': 'Manx,Manx-Gälisch',
    'mk': 'Mazedonisch',
    'mg': 'Malagasy, Malagassi',
    'ms': 'Malaiisch',
    'ml': 'Malayalam',
    'mt': 'Maltesisch',
    'mi': 'Maori',
    'mr': 'Marathi',
    'mh': 'Marshallesisch',
    'mn': 'Mongolisch',
    'na': 'Nauruisch',
    'nv': 'Navajo',
    'nd': 'Nord-Ndebele',
    'ne': 'Nepali',
    'ng': 'Ndonga',
    'nb': 'Bokmål',
    'nn': 'Nynorsk',
    'no': 'Norwegisch',
    'ii': 'Yi',
    'nr': 'Süd-Ndebele',
    'oc': 'Okzitanisch',
    'oj': 'Ojibwe',
    'cu': 'Kirchenslawisch, Altkirchenslawisch',
    'om': 'Oromo',
    'or': 'Oriya',
    'os': 'Ossetisch',
    'pa': 'Panjabi, Pandschabi',
    'pi': 'Pali',
    'fa': 'Persisch',
    'pl': 'Polnisch',
    'ps': 'Paschtunisch',
    'pt': 'Portugiesisch',
    'qu': 'Quechua',
    'rm': 'Bündnerromanisch, Romanisch',
    'rn': 'Kirundi',
    'ro': 'Rumänisch',
    'ru': 'Russisch',
    'sa': 'Sanskrit',
    'sc': 'Sardisch',
    'sd': 'Sindhi',
    'se': 'Nordsamisch',
    'sm': 'Samoanisch',
    'sg': 'Sango',
    'sr': 'Serbisch',
    'gd': 'Schottisch-gälisch',
    'sn': 'Shona',
    'si': 'Singhalesisch',
    'sk': 'Slowakisch',
    'sl': 'Slowenisch',
    'so': 'Somali',
    'st': 'Sesotho, Süd-Sotho',
    'es': 'Spanisch, Kastilisch',
    'su': 'Sundanesisch',
    'sw': 'Swahili',
    'ss': 'Siswati',
    'sv': 'Schwedisch',
    'ta': 'Tamil',
    'te': 'Telugu',
    'tg': 'Tadschikisch',
    'th': 'Thai',
    'ti': 'Tigrinya',
    'bo': 'Tibetisch',
    'tk': 'Turkmenisch',
    'tl': 'Tagalog',
    'tn': 'Setswana',
    'to': 'Tongaisch',
    'tr': 'Türkisch',
    'ts': 'Xitsonga',
    'tt': 'Tatarisch',
    'tw': 'Twi',
    'ty': 'Tahitianisch, Tahitisch',
    'ug': 'Uigurisch',
    'uk': 'Ukrainisch',
    'ur': 'Urdu',
    'uz': 'Usbekisch',
    've': 'Tshivenda',
    'vi': 'Vietnamesisch',
    'vo': 'Volapük',
    'wa': 'Wallonisch',
    'cy': 'Walisisch',
    'wo': 'Wolof',
    'fy': 'Westfriesisch',
    'xh': 'isiXhosa',
    'yi': 'Jiddisch',
    'yo': 'Yoruba',
    'za': 'Zhuang',
    'zu': 'isiZulu',
  };
}
